### ISSUE TITLE
making apibase to dynamic

### ISSUE THREAD

**Issue by MoonLGH** [xct007/nekopoi-scraper#14]
aku baru sadar, kayaknya apibase disini itu static ya, sebelumnya aku boleh tau ga, di sini ambil api urlnya dari mana ? apakah https capture neko android app ?

kalau begitu mungkin bisa buat third party api yg bakal throw api tiap request ?

**Comment by xct007** [comment]
Untuk API base yang dipakai di repo ini, iya itu dari neko. Belum, tidak ada niatan untuk membuat, dilihat dari structure repo saja sudah saya rasa berantakan, kalau kamu mau saya/kita untuk membuat nya, kamu bisa menjelaskan apa-apa saja yang dibutuhkan untuk membuat hal tersebut secara detail agar saya memahami.

> aku baru sadar, kayaknya apibase disini itu static ya, sebelumnya aku boleh tau ga, di sini ambil api urlnya dari mana ? apakah https capture neko android app ?
> 
> kalau begitu mungkin bisa buat third party api yg bakal throw api tiap request ?

**Comment by MoonLGH** [comment]
baiklah, kalau gitu aku izin copas beberapa kode ke [MoonLGH/nekoWrap](https://github.com/MoonLGH/nekoWrap) ya, aku mau buat pake api nya, nanti ku rombak abis abisan supaya api endpointnya dynamic engga static
